version: 0.0
os: linux
# files:
#   - source: docker/middleman_docker_image.tar.gz
#     destination: /tmp
hooks:
  TestStuff:
    - location: scripts/test.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/pull_image.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user
